[trainer]
    exp_name = 'celeba-glow'
    batch_size = 16
    learning_rate = 0.0001
    checkpoint_frequency = 2000

[data]
    name = 'image'
    path = 'data/celeba/img_align_celeba/'
    shape = [3, 128, 128]
    nb_bits = 5

[glow]
    nb_channels = 3
    nb_blocks = 5
    nb_flows = 32
    affine_coupling = false
