[trainer]
    exp_name = 'celeba-glow'
    batch_size = 128
    learning_rate = 0.0004
    checkpoint_frequency = 2000
    nb_batches = [16, 4]

[data]
    name = 'celeba'
    shape = [3, 64, 64]

[glow]
    nb_channels = 3
    nb_blocks = 4
    nb_flows = 32
