[trainer]
    exp_name = 'cifar10-glow'
    batch_size = 32
    learning_rate = 0.0004
    checkpoint_frequency = 1000

[data]
    name = 'cifar10'
    shape = [3, 32, 32]
    nb_bits = 5

[glow]
    nb_channels = 3
    nb_blocks = 3
    nb_flows = 32
    affine_coupling = true
