[trainer]
    exp_name = 'cifar10-glow'
    batch_size = 128
    learning_rate = 0.0004

[data]
    name = 'cifar10'
    shape = [3, 32, 32]

[glow]
    nb_channels = 3
    nb_blocks = 3
    nb_flows = 32
