[trainer]
    exp_name = 'ffhq128-glow'
    batch_size = 16
    learning_rate = 0.0001
    checkpoint_frequency = 5000

[data]
    name = 'image'
    path = 'data/ffhq1024'
    shape = [3, 256, 256]
    nb_bits = 5

[glow]
    nb_channels = 3
    nb_blocks = 6
    nb_flows = 64
    affine_coupling = false
