[trainer]
    exp_name = 'flowers-glow'
    batch_size = 128
    learning_rate = 0.0001
    checkpoint_frequency = 2000

[data]
    name = 'image'
    path = '~/datasets/flowers'
    shape = [3, 64, 64]
    nb_bits = 5

[glow]
    nb_channels = 3
    nb_blocks = 4
    nb_flows = 32
    affine_coupling = true
